"""add_client_portal_models

Revision ID: 2907a60186a8
Revises: 6040a75bbb78
Create Date: 2026-10-04 19:58:24.007098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2907a60186a8'
down_revision: Union[str, Sequence[str], None] = '6040a75bbb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='clientstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)

    op.create_table('client_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_activities_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_activities_organization_id'), ['organization_id'], unique=False)

    op.create_table('client_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_comments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_comments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_comments_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_comments_id'), ['id'], unique=False)

    op.create_table('client_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_invitations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invitations_organization_id'), ['organization_id'], unique=False)

    op.create_table('client_project_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'WRITE', name='clientprojectaccesslevel', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'project_id', name='uq_client_project_access')
    )
    with op.batch_alter_table('client_project_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_project_access_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_project_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_project_access_project_id'), ['project_id'], unique=False)

    op.create_table('client_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'IN_PROGRESS', 'WAITING_FOR_CLIENT', 'RESOLVED', 'CLOSED', name='clientrequeststatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='clientrequestpriority', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_requests_project_id'), ['project_id'], unique=False)

    op.create_table('client_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT_ADMIN', 'CLIENT_MEMBER', 'CLIENT_VIEWER', name='clientuserrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_user')
    )
    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_users_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_users_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_visible', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_visible', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_visible', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('client_visible')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('client_visible')

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_column('client_visible')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_users_id'))
        batch_op.drop_index(batch_op.f('ix_client_users_client_id'))

    op.drop_table('client_users')
    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_client_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_requests_id'))
        batch_op.drop_index(batch_op.f('ix_client_requests_client_id'))

    op.drop_table('client_requests')
    with op.batch_alter_table('client_project_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_project_access_project_id'))
        batch_op.drop_index(batch_op.f('ix_client_project_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_project_access_client_id'))

    op.drop_table('client_project_access')
    with op.batch_alter_table('client_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_invitations_id'))
        batch_op.drop_index(batch_op.f('ix_client_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_client_invitations_client_id'))

    op.drop_table('client_invitations')
    with op.batch_alter_table('client_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_comments_id'))
        batch_op.drop_index(batch_op.f('ix_client_comments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_client_comments_entity_id'))
        batch_op.drop_index(batch_op.f('ix_client_comments_client_id'))

    op.drop_table('client_comments')
    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_activities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_activities_id'))
        batch_op.drop_index(batch_op.f('ix_client_activities_event_type'))
        batch_op.drop_index(batch_op.f('ix_client_activities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_client_activities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_client_activities_client_id'))

    op.drop_table('client_activities')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    # ### end Alembic commands ###
