"""phase_19_governance

Revision ID: 6a96ca676a02
Revises: ab70f19762df
Create Date: 2026-10-04 06:55:20.094441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a96ca676a02'
down_revision: Union[str, Sequence[str], None] = 'ab70f19762df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_deletion_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_deletion_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_deletion_requests_user_id'), ['user_id'], unique=False)

    op.create_table('data_export_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_export_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_export_jobs_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_deletion_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_deletion_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_deletion_requests_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_domains_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_domains_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_identity_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('issuer_url', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('encrypted_client_secret', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_identity_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_identity_providers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_identity_providers_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_security_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=True),
    sa.Column('allow_member_api_keys', sa.Boolean(), nullable=True),
    sa.Column('allow_webhooks', sa.Boolean(), nullable=True),
    sa.Column('allow_github_integration', sa.Boolean(), nullable=True),
    sa.Column('allow_ai_features', sa.Boolean(), nullable=True),
    sa.Column('allow_external_integrations', sa.Boolean(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('max_active_sessions', sa.Integer(), nullable=True),
    sa.Column('password_expiry_days', sa.Integer(), nullable=True),
    sa.Column('login_failure_threshold', sa.Integer(), nullable=True),
    sa.Column('audit_retention_days', sa.Integer(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_security_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_security_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_security_policies_organization_id'), ['organization_id'], unique=True)

    op.create_table('security_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_approvals_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('security_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_security_approvals_id'))

    op.drop_table('security_approvals')
    with op.batch_alter_table('organization_security_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_security_policies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_security_policies_id'))

    op.drop_table('organization_security_policies')
    with op.batch_alter_table('organization_identity_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_identity_providers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_identity_providers_id'))

    op.drop_table('organization_identity_providers')
    with op.batch_alter_table('organization_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_domains_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_domains_id'))

    op.drop_table('organization_domains')
    with op.batch_alter_table('organization_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_deletion_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_deletion_requests_id'))

    op.drop_table('organization_deletion_requests')
    with op.batch_alter_table('data_export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_export_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_data_export_jobs_id'))

    op.drop_table('data_export_jobs')
    with op.batch_alter_table('user_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_deletion_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_deletion_requests_id'))

    op.drop_table('user_deletion_requests')
    # ### end Alembic commands ###
