"""add_workflow_models

Revision ID: 70994c719dcd
Revises: 2907a60186a8
Create Date: 2026-10-04 20:32:11.800413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70994c719dcd'
down_revision: Union[str, Sequence[str], None] = '2907a60186a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'DATETIME', 'BOOLEAN', 'SELECT', 'MULTI_SELECT', 'USER', 'PROJECT', 'CLIENT', name='customfieldtype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_org_custom_field_key')
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_fields_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_fields_organization_id'), ['organization_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Enum('TASK', 'CLIENT_REQUEST', 'RELEASE', 'DEPLOYMENT', 'CUSTOM', name='workflowentitytype', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_organization_id'), ['organization_id'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_values_custom_field_id'), ['custom_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_id'), ['id'], unique=False)

    op.create_table('workflow_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_forms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_forms_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_forms_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='uq_workflow_state_key')
    )
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_states_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('current_state_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['workflow_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_form_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_form_fields_custom_field_id'), ['custom_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_form_fields_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_form_fields_id'), ['id'], unique=False)

    op.create_table('workflow_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from_state_id', sa.UUID(), nullable=False),
    sa.Column('to_state_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['workflow_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_state_id'], ['workflow_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_transitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_transitions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transition_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE_TASK', 'UPDATE_TASK', 'SEND_NOTIFICATION', 'CREATE_AUDIT_EVENT', 'REQUEST_APPROVAL', 'TRIGGER_AUTOMATION', name='workflowactiontype', native_enum=False), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_actions_transition_id'), ['transition_id'], unique=False)

    op.create_table('workflow_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_transition_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'CANCELLED', name='workflowapprovalstatus', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_transition_id'], ['workflow_transitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_approvals_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approvals_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_approvals_workflow_transition_id'), ['workflow_transition_id'], unique=False)

    op.create_table('workflow_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transition_id', sa.UUID(), nullable=False),
    sa.Column('condition_type', sa.Enum('ALL', 'ANY', 'NOT', 'FIELD_EQUALS', 'FIELD_GREATER', name='workflowconditiontype', native_enum=False), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_conditions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_conditions_transition_id'), ['transition_id'], unique=False)

    op.create_table('workflow_execution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_state_id', sa.UUID(), nullable=True),
    sa.Column('to_state_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_execution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_execution_events_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_execution_events_id'), ['id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('client_comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('client_invitations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('client_project_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_project_access', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_invitations', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_comments', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('client_activities', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('workflow_execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_execution_events_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_execution_events_execution_id'))

    op.drop_table('workflow_execution_events')
    with op.batch_alter_table('workflow_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_conditions_transition_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_conditions_id'))

    op.drop_table('workflow_conditions')
    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_workflow_transition_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_entity_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_approvals_entity_id'))

    op.drop_table('workflow_approvals')
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_actions_transition_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_actions_id'))

    op.drop_table('workflow_actions')
    with op.batch_alter_table('workflow_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_transitions_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_transitions_id'))

    op.drop_table('workflow_transitions')
    with op.batch_alter_table('workflow_form_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_form_fields_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_form_fields_form_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_form_fields_custom_field_id'))

    op.drop_table('workflow_form_fields')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_entity_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_entity_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_states_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_states_id'))

    op.drop_table('workflow_states')
    with op.batch_alter_table('workflow_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_forms_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_forms_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_forms_id'))

    op.drop_table('workflow_forms')
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_values_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_entity_type'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_entity_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_custom_field_id'))

    op.drop_table('custom_field_values')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_entity_type'))

    op.drop_table('workflows')
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_fields_organization_id'))
        batch_op.drop_index(batch_op.f('ix_custom_fields_id'))

    op.drop_table('custom_fields')
    # ### end Alembic commands ###
