"""advanced_tasks

Revision ID: 73431a3a65f9
Revises: e8ae6919d6f0
Create Date: 2026-10-03 17:45:46.299247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73431a3a65f9'
down_revision: Union[str, Sequence[str], None] = 'e8ae6919d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_label_org_name')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labels_organization_id'), ['organization_id'], unique=False)

    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title_template', sa.String(), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('priority_template', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority', native_enum=False), nullable=True),
    sa.Column('labels_template', sa.JSON(), nullable=True),
    sa.Column('checklist_template', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_items_task_id'), ['task_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'RELATES_TO', name='taskdependencytype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'dependency_type', name='uq_task_dependency')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_target_id'), ['target_id'], unique=False)

    op.create_table('task_labels',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id')
    )
    op.create_table('task_watchers',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('task_seq_num', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_key'), ['key'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('estimate_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimate_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recurring_config', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_key'), ['task_key'], unique=True)
        batch_op.create_foreign_key('fk_tasks_parent_id_tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_tasks_updated_by_id_users', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')


    # Data migration: Populate project.key and task.task_key
    connection = op.get_bind()
    
    # 1. Update Projects
    projects = connection.execute(sa.text("SELECT id, name FROM projects")).fetchall()
    for proj in projects:
        # Generate a key: e.g. "DevFlow" -> "DEV"
        name_parts = proj.name.upper().split()
        if len(name_parts) >= 2:
            key = name_parts[0][:1] + name_parts[1][:2]
        else:
            key = proj.name.upper()[:3]
        if not key.strip():
            key = "PROJ"
        # make it alphanumeric only
        key = ''.join(e for e in key if e.isalnum())
        
        # update project
        connection.execute(sa.text("UPDATE projects SET key = :key WHERE id = :id"), {"key": key, "id": proj.id})
        
        # 2. Update Tasks for this project
        tasks = connection.execute(sa.text("SELECT id FROM tasks WHERE project_id = :pid ORDER BY created_at ASC"), {"pid": proj.id}).fetchall()
        for idx, task in enumerate(tasks):
            seq = idx + 1
            task_key = f"{key}-{seq}"
            connection.execute(sa.text("UPDATE tasks SET task_key = :tkey, position = :pos WHERE id = :tid"), 
                               {"tkey": task_key, "pos": float(seq), "tid": task.id})
        
        # Update sequence
        connection.execute(sa.text("UPDATE projects SET task_seq_num = :seq WHERE id = :id"), {"seq": len(tasks), "id": proj.id})
        

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Autogenerated directives were `drop_constraint(None, ...)`, which is
        # guaranteed to fail (no name). Use the names created in upgrade().
        batch_op.drop_constraint('fk_tasks_parent_id_tasks', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_updated_by_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_task_key'))
        batch_op.drop_index(batch_op.f('ix_tasks_position'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_column('recurring_config')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('position')
        batch_op.drop_column('actual_hours')
        batch_op.drop_column('estimate_hours')
        batch_op.drop_column('estimate_points')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('task_key')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_key'))
        batch_op.drop_column('task_seq_num')
        batch_op.drop_column('key')

    op.drop_table('task_watchers')
    op.drop_table('task_labels')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_target_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_source_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_task_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_items_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_task_templates_id'))

    op.drop_table('task_templates')
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_organization_id'))
        batch_op.drop_index(batch_op.f('ix_labels_id'))

    op.drop_table('labels')

    # Data migration: Populate project.key and task.task_key
    connection = op.get_bind()
    
    # 1. Update Projects
    projects = connection.execute(sa.text("SELECT id, name FROM projects")).fetchall()
    for proj in projects:
        # Generate a key: e.g. "DevFlow" -> "DEV"
        name_parts = proj.name.upper().split()
        if len(name_parts) >= 2:
            key = name_parts[0][:1] + name_parts[1][:2]
        else:
            key = proj.name.upper()[:3]
        if not key.strip():
            key = "PROJ"
        # make it alphanumeric only
        key = ''.join(e for e in key if e.isalnum())
        
        # update project
        connection.execute(sa.text("UPDATE projects SET key = :key WHERE id = :id"), {"key": key, "id": proj.id})
        
        # 2. Update Tasks for this project
        tasks = connection.execute(sa.text("SELECT id FROM tasks WHERE project_id = :pid ORDER BY created_at ASC"), {"pid": proj.id}).fetchall()
        for idx, task in enumerate(tasks):
            seq = idx + 1
            task_key = f"{key}-{seq}"
            connection.execute(sa.text("UPDATE tasks SET task_key = :tkey, position = :pos WHERE id = :tid"), 
                               {"tkey": task_key, "pos": float(seq), "tid": task.id})
        
        # Update sequence
        connection.execute(sa.text("UPDATE projects SET task_seq_num = :seq WHERE id = :id"), {"seq": len(tasks), "id": proj.id})
        

    # ### end Alembic commands ###
