"""Add advanced notifications fields

Revision ID: 86f704f37613
Revises: b27b8e7e4ff4
Create Date: 2026-10-05 14:14:12.482645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f704f37613'
down_revision: Union[str, Sequence[str], None] = 'b27b8e7e4ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_report_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('deployment_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('release_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('job_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('automation_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('workflow_approval_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('client_request_notifications', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('team_activity_notifications', sa.Boolean(), server_default='1', nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('action_required', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('important', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_notifications_action_required'), ['action_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_important'), ['important'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_notifications_org_id', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

def downgrade() -> None:
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_org_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_important'))
        batch_op.drop_index(batch_op.f('ix_notifications_action_required'))
        batch_op.drop_column('important')
        batch_op.drop_column('action_required')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_column('team_activity_notifications')
        batch_op.drop_column('client_request_notifications')
        batch_op.drop_column('workflow_approval_notifications')
        batch_op.drop_column('automation_notifications')
        batch_op.drop_column('job_notifications')
        batch_op.drop_column('release_notifications')
        batch_op.drop_column('deployment_notifications')
        batch_op.drop_column('daily_report_notifications')