"""add time tracking

Revision ID: 94568e164f19
Revises: f0e29dd136f2
Create Date: 2026-10-03 20:09:14.007772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94568e164f19'
down_revision: Union[str, Sequence[str], None] = 'f0e29dd136f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_timers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_active_timer_user_org')
    )
    with op.batch_alter_table('active_timers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_timers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_timers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_timers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_timers_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_timers_user_id'), ['user_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('TIMER', 'MANUAL', name='timeentrysource', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_billable'), ['billable'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_billable'))

    op.drop_table('time_entries')
    with op.batch_alter_table('active_timers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_timers_user_id'))
        batch_op.drop_index(batch_op.f('ix_active_timers_task_id'))
        batch_op.drop_index(batch_op.f('ix_active_timers_project_id'))
        batch_op.drop_index(batch_op.f('ix_active_timers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_active_timers_id'))

    op.drop_table('active_timers')
    # ### end Alembic commands ###
