"""implement AI engineering intelligence platform

Revision ID: 9d8415d24669
Revises: 1c483d67289a
Create Date: 2026-10-04 18:43:39.456083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8415d24669'
down_revision: Union[str, Sequence[str], None] = '1c483d67289a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usages_user_id'), ['user_id'], unique=False)

    op.create_table('ai_project_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_project_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_project_memories_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_project_memories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_project_memories_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_project_memories_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    with op.batch_alter_table('ai_project_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_project_memories_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_project_memories_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_project_memories_id'))
        batch_op.drop_index(batch_op.f('ix_ai_project_memories_category'))

    op.drop_table('ai_project_memories')
    with op.batch_alter_table('ai_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usages_id'))

    op.drop_table('ai_usages')
