"""Add Sprint and Milestone models

Revision ID: b950dc62515d
Revises: 73431a3a65f9
Create Date: 2026-10-03 19:05:38.600311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b950dc62515d'
down_revision: Union[str, Sequence[str], None] = '73431a3a65f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='milestonestatus', native_enum=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)

    op.create_table('sprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='sprintstatus', native_enum=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_sprints_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_status'), ['status'], unique=False)

    op.create_table('sprint_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sprint_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('completed_points', sa.Float(), nullable=False),
    sa.Column('remaining_points', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprint_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprint_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprint_snapshots_sprint_id'), ['sprint_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('milestone_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_sprint_id', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_tasks_milestone_id', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_sprint_id', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_milestone_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_column('milestone_id')
        batch_op.drop_column('sprint_id')

    with op.batch_alter_table('sprint_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprint_snapshots_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_sprint_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_sprint_snapshots_id'))

    op.drop_table('sprint_snapshots')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_status'))
        batch_op.drop_index(batch_op.f('ix_sprints_project_id'))
        batch_op.drop_index(batch_op.f('ix_sprints_name'))
        batch_op.drop_index(batch_op.f('ix_sprints_key'))
        batch_op.drop_index(batch_op.f('ix_sprints_id'))
        batch_op.drop_index(batch_op.f('ix_sprints_end_date'))

    op.drop_table('sprints')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_name'))
        batch_op.drop_index(batch_op.f('ix_milestones_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_due_date'))

    op.drop_table('milestones')
    # ### end Alembic commands ###
