"""Phase 32 release models

Revision ID: d36b2909d14d
Revises: d4e5f6a7b8c9
Create Date: 2026-10-05 10:54:07.753793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b2909d14d'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVOKED', name='releaseapprovalstatus', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_approvals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_approvals_release_id'), ['release_id'], unique=False)

    # NOTE: `_alembic_tmp_attachments` is an alembic batch-operation artifact
    # that existed on the dev database when this migration was autogenerated.
    # It was never part of the real schema, so it may not exist (fresh DBs);
    # drop it only if present, and never recreate it in downgrade.
    if sa.inspect(op.get_bind()).has_table('_alembic_tmp_attachments'):
        op.drop_table('_alembic_tmp_attachments')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployment_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rollback_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'READY', 'APPROVED', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'ROLLED_BACK', 'CANCELLED', name='releasestatus', native_enum=False),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_releases_approved_by_id', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_key'))
        batch_op.create_index(batch_op.f('ix_sprints_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_key'))
        batch_op.create_index(batch_op.f('ix_sprints_key'), ['key'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_releases_approved_by_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'READY', 'APPROVED', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'ROLLED_BACK', 'CANCELLED', name='releasestatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('rollback_timestamp')
        batch_op.drop_column('deployment_timestamp')

    # NOTE: an autogenerated `op.create_table('_alembic_tmp_attachments', ...)`
    # was removed here — that table was an alembic batch-operation artifact,
    # never part of the real schema, so downgrade must not recreate it.
    with op.batch_alter_table('release_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_approvals_release_id'))
        batch_op.drop_index(batch_op.f('ix_release_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_release_approvals_id'))

    op.drop_table('release_approvals')
    # ### end Alembic commands ###
