"""add_delivery_models

Revision ID: eb635a9705af
Revises: 94568e164f19
Create Date: 2026-10-03 20:29:08.371406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb635a9705af'
down_revision: Union[str, Sequence[str], None] = '94568e164f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_environment_name_project')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'READY', 'RELEASED', 'CANCELLED', name='releasestatus', native_enum=False), nullable=False),
    sa.Column('release_type', sa.Enum('MAJOR', 'MINOR', 'PATCH', 'HOTFIX', name='releasetype', native_enum=False), nullable=False),
    sa.Column('target_environment', sa.String(), nullable=True),
    sa.Column('git_tag', sa.String(), nullable=True),
    sa.Column('target_commit_sha', sa.String(), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_release_version_project')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_status'), ['status'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'ROLLED_BACK', name='deploymentstatus', native_enum=False), nullable=False),
    sa.Column('deployment_url', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('MOCK', 'GITHUB_ACTIONS', 'MANUAL', name='deploymentprovider', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('previous_deployment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)

    op.create_table('release_pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.String(), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id', 'pr_number', name='uq_release_pr')
    )
    with op.batch_alter_table('release_pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_pull_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_pull_requests_release_id'), ['release_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('MOCK', 'GITHUB_ACTIONS', 'MANUAL', name='deploymentprovider', native_enum=False), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='pipelinestatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('workflow_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_status'), ['status'], unique=False)

    op.create_table('release_tasks',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('release_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_tasks')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_release_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_commit_sha'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('release_pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_pull_requests_release_id'))
        batch_op.drop_index(batch_op.f('ix_release_pull_requests_id'))

    op.drop_table('release_pull_requests')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_started_at'))
        batch_op.drop_index(batch_op.f('ix_deployments_release_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_environment_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_completed_at'))
        batch_op.drop_index(batch_op.f('ix_deployments_commit_sha'))

    op.drop_table('deployments')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_status'))
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))
        batch_op.drop_index(batch_op.f('ix_releases_organization_id'))
        batch_op.drop_index(batch_op.f('ix_releases_id'))
        batch_op.drop_index(batch_op.f('ix_releases_created_at'))

    op.drop_table('releases')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_environments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_environments_id'))

    op.drop_table('environments')
    # ### end Alembic commands ###
