"""add_infrastructure_models

Revision ID: ec2b93e3c3a3
Revises: cbb9eba7886b
Create Date: 2026-10-04 07:11:39.504969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2b93e3c3a3'
down_revision: Union[str, Sequence[str], None] = 'cbb9eba7886b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environment_variables_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_variables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environment_variables_organization_id'), ['organization_id'], unique=False)

    op.create_table('service_health',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', 'UNKNOWN', name='servicehealthstatus', native_enum=False), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_health_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_health_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_health_organization_id'), ['organization_id'], unique=False)

    op.create_table('deployment_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='deploymentapprovalstatus', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_approvals_organization_id'), ['organization_id'], unique=False)

    op.create_table('deployment_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', name='deploymentincidentstatus', native_enum=False), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_incidents_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_incidents_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_incidents_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployment_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=True))

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('environment_type', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', 'PREVIEW', name='environmenttype', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEGRADED', 'DOWN', name='environmentstatus', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('status')
        batch_op.drop_column('environment_type')
        batch_op.drop_column('slug')

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_column('branch')
        batch_op.drop_column('version')
        batch_op.drop_column('deployment_key')

    with op.batch_alter_table('deployment_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_incidents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_incidents_environment_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_incidents_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_incidents_created_at'))

    op.drop_table('deployment_incidents')
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_created_at'))

    op.drop_table('deployment_approvals')
    with op.batch_alter_table('service_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_health_organization_id'))
        batch_op.drop_index(batch_op.f('ix_service_health_id'))
        batch_op.drop_index(batch_op.f('ix_service_health_environment_id'))

    op.drop_table('service_health')
    with op.batch_alter_table('environment_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environment_variables_organization_id'))
        batch_op.drop_index(batch_op.f('ix_environment_variables_id'))
        batch_op.drop_index(batch_op.f('ix_environment_variables_environment_id'))

    op.drop_table('environment_variables')
    # ### end Alembic commands ###
