"""Make org nullable

Revision ID: f0e29dd136f2
Revises: 4554a8dfe06a
Create Date: 2026-10-03 19:49:17.634618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e29dd136f2'
down_revision: Union[str, Sequence[str], None] = '4554a8dfe06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
