"""Add GitHub integration models

Revision ID: fcbc123cd696
Revises: cb0e83f73b05
Create Date: 2026-10-03 15:53:51.614027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbc123cd696'
down_revision: Union[str, Sequence[str], None] = 'cb0e83f73b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('github_user_id', sa.String(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=False),
    sa.Column('github_avatar_url', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connections_github_user_id'), 'github_connections', ['github_user_id'], unique=True)
    op.create_index(op.f('ix_github_connections_id'), 'github_connections', ['id'], unique=False)
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=True)
    op.create_table('project_github_repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('github_repository_id', sa.String(), nullable=False),
    sa.Column('github_owner', sa.String(), nullable=False),
    sa.Column('github_name', sa.String(), nullable=False),
    sa.Column('github_full_name', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_github_repositories_id'), 'project_github_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_project_github_repositories_project_id'), 'project_github_repositories', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_github_repositories_project_id'), table_name='project_github_repositories')
    op.drop_index(op.f('ix_project_github_repositories_id'), table_name='project_github_repositories')
    op.drop_table('project_github_repositories')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_index(op.f('ix_github_connections_id'), table_name='github_connections')
    op.drop_index(op.f('ix_github_connections_github_user_id'), table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
